### ISSUE TITLE
"missing separator" error with Makefile

### ISSUE THREAD

**Issue by spookylukey** [victorvde/jpeg2png#2]
Following the installation instructions for 1.0 release, I get this error:

```
Makefile:4: *** missing separator. Stop.
```

This is with GNU Make 3.8.1

Adding a tab to the beginning of line 4 "fixes" it, at least so I get a working compilation, I'm not sure this is the correct fix though.

**Comment by victorvde** [comment]
Fixed in 2f812561, thanks!
